version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_container
    ports:
      - '3001:3001'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leonardoAI
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
