version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_container
    environment:
      PORT: 3001
      DATABASE_URL: 'postgresql://postgres:password123@postgres:5432/leonardoAI?schema=public'
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leonardoAI
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      retries: 5
      timeout: 5s
